### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by A1essandro** [phpmath/vector#1]
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phpmath/vector dev-master -> satisfiable by phpmath/vector[dev-master].
    - phpmath/vector dev-master requires phpmath/bignumber dev-master -> no matching package found.
```

It's error after `composer require phpmath/vector dev-master`

**Comment by waltertamboer** [comment]
I'll have a look at this right now.

**Comment by waltertamboer** [comment]
@A1essandro The correct syntax is `composer require phpmath/vector:dev-master`. I've created a 1.0.0 tag for all phpmath libraries so you can now simply run `composer require phpmath/vector` and it will install version 1.0.0. Have fun.

**Comment by A1essandro** [comment]
Oh! Sorry, my mistake! Thank you!

**Comment by waltertamboer** [comment]
No problem, you're welcome :+1:
