### ISSUE TITLE
[Insight] Usage of a function in loops should be avoided - in src/Vector.php, line 52

### ISSUE THREAD

**Issue by oliworx** [phpmath/vector#3]
**[in src/Vector.php, line 52](https://github.com/phpmath/vector/blob/3a88215b8e561f0361b359ecd196bba7b1384eea/src/Vector.php#L52)**

> This loop uses a function. To avoid the overhead of executing the function n times, you should precalculate it before the loop.

``` php
            throw new InvalidArgumentException('Invalid vector provided. The size should be the same.');
        }

        $result = new BigNumber();

        for ($i = 0; $i < $this->getSize(); ++$i) {
            $value = new BigNumber($this[$i]);
            $value->multiply($vector[$i]);

            $result->add($value);
        }
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/543e6009-49ee-4239-91c4-985cfdd32d50/analyses/11)_

**Comment by waltertamboer** [comment]
Fixed with PR #4
